
---
- hosts: web
  tasks:
     - package:
           name: httpd
           state: present
     - copy:
           src: /webcontent/ansible/my.conf
           dest: /etc/httpd/conf.d
     - copy:
           src: /webcontent/index.html
           dest: /final/

     - service:
           name: httpd
           state: restarted
            
